// Pays courants (en haut) puis liste complète, triée
export const PAYS_COURANTS = [
  { code: 'FR', nom: 'France' },
  { code: 'BE', nom: 'Belgique' },
  { code: 'CH', nom: 'Suisse' },
  { code: 'DE', nom: 'Allemagne' },
  { code: 'ES', nom: 'Espagne' },
  { code: 'IT', nom: 'Italie' },
  { code: 'GB', nom: 'Royaume-Uni' },
  { code: 'NL', nom: 'Pays-Bas' },
  { code: 'LU', nom: 'Luxembourg' },
  { code: 'PT', nom: 'Portugal' },
]

export const PAYS_TOUS = [
  { code: 'AT', nom: 'Autriche' },
  { code: 'AU', nom: 'Australie' },
  { code: 'BR', nom: 'Brésil' },
  { code: 'BG', nom: 'Bulgarie' },
  { code: 'CA', nom: 'Canada' },
  { code: 'CN', nom: 'Chine' },
  { code: 'HR', nom: 'Croatie' },
  { code: 'CZ', nom: 'Tchéquie' },
  { code: 'DK', nom: 'Danemark' },
  { code: 'EE', nom: 'Estonie' },
  { code: 'FI', nom: 'Finlande' },
  { code: 'GR', nom: 'Grèce' },
  { code: 'HU', nom: 'Hongrie' },
  { code: 'IE', nom: 'Irlande' },
  { code: 'IS', nom: 'Islande' },
  { code: 'JP', nom: 'Japon' },
  { code: 'LV', nom: 'Lettonie' },
  { code: 'LT', nom: 'Lituanie' },
  { code: 'MA', nom: 'Maroc' },
  { code: 'MX', nom: 'Mexique' },
  { code: 'NO', nom: 'Norvège' },
  { code: 'PL', nom: 'Pologne' },
  { code: 'RO', nom: 'Roumanie' },
  { code: 'RS', nom: 'Serbie' },
  { code: 'SK', nom: 'Slovaquie' },
  { code: 'SI', nom: 'Slovénie' },
  { code: 'SE', nom: 'Suède' },
  { code: 'TR', nom: 'Turquie' },
  { code: 'US', nom: 'États-Unis' },
]